sudo: false
language: python
notifications:
  email: false
python:
  - pypy-5.3.1
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6
before_install:
  - pip install -r test/requirements.txt
script:
  - nosetests test
