sudo: false
language: python
notifications:
  email:
    - chenjiandongx@qq.com
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
before_install:
  - pip install -r test/requirements.txt
script:
  - make tests
after_success:
  codecov

